# Generated by Django 3.1.6 on 2021-03-13 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lname',
        ),
    ]
