# Generated by Django 3.1.6 on 2021-03-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210313_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='terms_condition',
            field=models.BooleanField(default=False),
        ),
    ]
